apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard    
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
